spring:
  application:
    name: service-test1
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 10012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/