eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: zuul
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: gateway
    api-b:
      path: /api-b/**
      serviceId: gateway2